---
- name: install ansible.builtin.pip module dependencies
  ansible.builtin.apt:
    name: "{{ docker_ansible_dependencies_apt }}"
    state: present
    force_apt_get: yes

- name: install dependencies of community.docker modules
  ansible.builtin.pip:
    name: "{{ docker_ansible_dependencies_pip }}"
    state: present
