---
- name: install pip module dependencies
  apt:
    name:
      - python3-pip
      - python3-setuptools
      - python3-virtualenv
    state: present
    force_apt_get: yes

- name: install dependencies of Ansible modules that manage Docker
  pip:
    name:
      - docker>=1.10.0
      - PyYAML>=3.11
    state: present

# docker_compose module dependency
- name: install Docker Compose Python package
  pip:
    name: "{{ docker_compose_package }}"
    state: present
  when: docker_compose_package_install
