---
- name: check whether iptables filter rules have been changed
  ansible.builtin.command: "{{ docker_iptables_executable }} --table=filter --list-rules"
  changed_when: "'-N DOCKER' not in _result.stdout_lines"
  register: _result
  notify: restart daemon

- name: check whether iptables nat rules have been changed
  ansible.builtin.command: "{{ docker_iptables_executable }} --table=nat --list-rules"
  changed_when: "'-N DOCKER' not in _result.stdout_lines"
  register: _result
  notify: restart daemon
