---
- name: check whether iptables filter rules have been changed
  command: "{{ docker_iptables_executable }} --table=filter --list-rules"
  changed_when: "'-N DOCKER' not in docker_iptables_filter_info.stdout_lines"
  register: docker_iptables_filter_info
  notify: restart daemon

- name: check whether iptables nat rules have been changed
  command: "{{ docker_iptables_executable }} --table=nat --list-rules"
  changed_when: "'-N DOCKER' not in docker_iptables_nat_info.stdout_lines"
  register: docker_iptables_nat_info
  notify: restart daemon
