---
- name: get version of installed Docker Compose
  command: docker-compose version --short
  register: _result
  changed_when: no
  failed_when: no

- name: declare version of installed Docker Compose
  set_fact:
    _compose_binary_current_version: "{{ _result.stdout|trim }}"
  when: _result.stdout is defined

- name: set docker_compose_binary_version
  when: docker_compose_binary_version is undefined
  block:
    - name: get Docker Compose latest release info
      uri:
        url: "{{ docker_compose_binary_latest_release_info_url }}"
      register: _result

    - name: declare Docker Compose version to install
      set_fact:
        docker_compose_binary_version: "{{ _result.json.name }}"

- name: install Docker Compose
  get_url:
    url: "{{ docker_compose_binary_download_url }}"
    dest: "{{ docker_compose_binary_path }}"
    mode: u=rwx,g=rx,o=rx
  when: >
    _compose_binary_current_version is undefined
    or docker_compose_binary_version != _compose_binary_current_version
