---
- name: install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      # required by ansible.builtin.apt_key module
      - gnupg
    state: present
    force_apt_get: yes
    update_cache: yes

- name: add Docker apt key
  ansible.builtin.apt_key:
    url: "{{ docker_apt_key_url }}"
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ docker_apt_sources_arch }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] {{ docker_apt_sources_uri }} {{ docker_apt_sources_suite }} stable"
    state: present
    filename: docker

- name: install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    force_apt_get: yes
    update_cache: yes

- name: install Docker Compose
  ansible.builtin.apt:
    name:
      - docker-compose-plugin
    state: present
    force_apt_get: yes
    update_cache: yes

- name: create config directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: u=rwx,g=,o=

- name: set daemon config
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    lstrip_blocks: yes
    mode: u=rw,g=,o=
  notify:
    - restart daemon

- name: start and enable daemon
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: yes

- name: check whether iptables rules have been changed
  ansible.builtin.import_tasks: check-iptables.yml
  when: docker_iptables_check

- name: restart on daemon config or iptables rules change
  ansible.builtin.meta: flush_handlers
