---
- name: install Docker Engine
  import_tasks: engine.yml

- name: install Docker Compose
  import_tasks: compose.yml

- name: install dependencies of Ansible modules that manage Docker
  import_tasks: ansible-docker-dependencies.yml
  when: docker_modules_dependencies_install
