---
- name: install Docker
  ansible.builtin.import_tasks: docker.yml

- name: install dependencies of Ansible modules that manage Docker
  ansible.builtin.import_tasks: ansible-dependencies.yml
  when: docker_ansible_dependencies_install
