---
- name: verify
  hosts: instance
  tasks:
    - name: flush filter table
      ansible.builtin.command: iptables --table=filter --flush
      changed_when: yes

    - name: delete user-defined chains in filter table
      ansible.builtin.command: iptables --table=filter --delete-chain
      changed_when: yes

    - name: flush nat table
      ansible.builtin.command: iptables --table=nat --flush
      changed_when: yes

    - name: delete user-defined chains in nat table
      ansible.builtin.command: iptables --table=nat --delete-chain
      changed_when: yes

    - name: fix iptables rules
      ansible.builtin.import_role:
        name: yabusygin.docker
      vars:
        docker_ansible_dependencies_install: no

    - name: get filter table rules
      ansible.builtin.command: iptables --table=filter --list-rules
      changed_when: no
      register: _result

    - name: check filter table rules
      ansible.builtin.assert:
        that: "'-N DOCKER' in _result.stdout"

    - name: get nat table rules
      ansible.builtin.command: iptables --table=nat --list-rules
      changed_when: no
      register: _result

    - name: check nat table rules
      ansible.builtin.assert:
        that: "'-N DOCKER' in _result.stdout"
