---
ansible_python_interpreter: python3

docker_log_driver: journald
docker_log_options:
  - name: tag
    value: "{% raw %}{{.Name}}/{{.FullID}}{% endraw %}"
  - name: env
    value:
      - TEST1
      - TEST2
