---
name: test
on:
  push:
    branches:
      - "**"
jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - "geerlingguy/docker-debian10-ansible:latest"
          - "geerlingguy/docker-debian11-ansible:latest"
          - "geerlingguy/docker-ubuntu1804-ansible:latest"
          - "geerlingguy/docker-ubuntu2004-ansible:latest"
        scenario:
          - default
          - userns_remap
    defaults:
      run:
        working-directory: docker
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          path: docker

      - name: set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: install dependencies
        run: python -m pip install --requirement=requirements.txt

      - name: run templates rendering tests
        run: templtest

      - name: run molecule tests
        run: molecule test --scenario-name=$TEST_SCENARIO
        env:
          TEST_IMAGE: ${{ matrix.image }}
          TEST_SCENARIO: ${{ matrix.scenario }}
